name: Build_CI_Vue_Dev

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "**/README.md"
      - "**/dependabot.yml"
      - ".github/workflows/develop_CD.yml"
      - ".github/workflows/main_CD.yml"
    branches:
      - develop

concurrency: develop_CI

jobs:
  build-ci:
    name: "Build and CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cypress CI Run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build:development
          start: npm run serve
          wait-on: "http://localhost:3000"
          config-file: cypress/envs/cypress.ci.json

  automerge:
    needs: build-ci
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
