name: Build_CI_Vue_Prod

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "**/README.md"
      - "**/dependabot.yml"
      - ".github/workflows/develop_CD.yml"
      - ".github/workflows/main_CD.yml"
    branches:
      - main

concurrency: main_CI

jobs:
  build-ci:
    name: "Build and CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cypress CI Run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build:production
          start: npm run serve -- -p 4200
          wait-on: "http://localhost:4200"
          config-file: cypress.config.ci.js
